# Generated by Django 2.2.6 on 2019-12-02 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import weblets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presenters', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weblet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('deleted', 'Deleted')], default='draft', max_length=10)),
                ('picture_thumbnail', models.ImageField(upload_to=weblets.models.picture_thumbnail_path)),
                ('picture_large', models.ImageField(upload_to=weblets.models.picture_large_path)),
                ('tags', models.TextField(blank=True, null=True)),
                ('webinar_recording_link', models.CharField(max_length=512)),
                ('watcher_signup_required', models.BooleanField(default=False)),
                ('publish_on_lw_website', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('last_modified_on', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='weblet', to='accounts.Account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weblet_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weblet_modified_by', to=settings.AUTH_USER_MODEL)),
                ('presenters', models.ManyToManyField(blank=True, to='presenters.Presenter')),
            ],
            options={
                'ordering': ('-created_on', '-last_modified_on'),
            },
        ),
    ]
