# Generated by Django 2.2.6 on 2020-01-14 03:40

from django.db import migrations, models
import weblets.models


class Migration(migrations.Migration):

    dependencies = [
        ('weblets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblet',
            name='picture_large',
            field=models.ImageField(blank=True, null=True, upload_to=weblets.models.picture_large_path),
        ),
        migrations.AlterField(
            model_name='weblet',
            name='picture_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=weblets.models.picture_thumbnail_path),
        ),
    ]
