# Generated by Django 2.2.6 on 2019-12-02 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import presenters.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('linked_in_url', models.TextField(blank=True, null=True)),
                ('twitter_handle', models.TextField(blank=True, null=True)),
                ('picture_thumbnail', models.ImageField(blank=True, null=True, upload_to=presenters.models.picture_thumbnail_path)),
                ('picture_large', models.ImageField(blank=True, null=True, upload_to=presenters.models.picture_large_path)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('last_modified_on', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='presenter', to='accounts.Account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presenter_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presenter_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
