# Generated by Django 2.2.6 on 2019-12-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='sharable_script',
            field=models.TextField(blank=True),
        ),
    ]
