# Generated by Django 2.2.6 on 2019-12-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='organisation_name',
            new_name='organization_name',
        ),
    ]
