# Generated by Django 2.2.6 on 2020-01-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_by',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_modified_by',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
